/**
 * Dhaka content, part 5 (migration 0017): haleem, pitha and breakfast (nashta) places.
 * Same rules as dhaka-data.ts: only what published articles say, no prices or ratings. Sources in
 * docs/content-sources.md. Shops move and close, so contributors confirm through the verify flow.
 */
import type { DhakaSet } from "./dhaka-data";

export const DHAKA_SET_5: DhakaSet = {
  migration: "0017_seed_dhaka_5.sql",
  number: "0017",
  fameSortStart: 30,
  areas: [
    { slug: "kalabagan", nameBn: "কলাবাগান", nameEn: "Kalabagan" },
    { slug: "gopibag", nameBn: "গোপীবাগ", nameEn: "Gopibag" },
    { slug: "motijheel", nameBn: "মতিঝিল", nameEn: "Motijheel" },
    { slug: "banglabazar", nameBn: "বাংলাবাজার", nameEn: "Banglabazar" },
    { slug: "hathkhola", nameBn: "হাতখোলা", nameEn: "Hathkhola" },
    { slug: "chankharpul", nameBn: "চানখারপুল", nameEn: "Chankharpul" },
    { slug: "baily-road", nameBn: "বেইলি রোড", nameEn: "Baily Road" },
    { slug: "shantinagar", nameBn: "শান্তিনগর", nameEn: "Shantinagar" },
  ],
  foods: [
    {
      slug: "luchi",
      nameBn: "লুচি",
      nameEn: "Luchi",
      aboutBn: "ময়দার ফোলা ভাজা রুটি। সকালে আলুর দম, ডাল বা হালুয়ার সঙ্গে খাওয়া হয়।",
      aliases: ["luci", "loochi"],
    },
    {
      slug: "puri-bhaji",
      nameBn: "পুরি-ভাজি",
      nameEn: "Puri Bhaji",
      aboutBn: "ভাজা পুরির সঙ্গে সবজির ভাজি। ঢাকার পরিচিত সকালের নাশতা।",
      aliases: ["puri bhaji", "puri", "poori bhaji", "পুরি ভাজি"],
    },
    {
      slug: "paratha-bhaji",
      nameBn: "পরোটা-ভাজি",
      nameEn: "Paratha Bhaji",
      aboutBn: "পরোটার সঙ্গে সবজির ভাজি। সকালের নাশতার পরিচিত পদ।",
      aliases: ["porota bhaji", "paratha bhaji", "পরোটা ভাজি", "parota bhaji"],
    },
    {
      slug: "paya",
      nameBn: "পায়া",
      nameEn: "Paya",
      aboutBn: "গরু বা খাসির পায়ার ঘন ঝোল। পুরান ঢাকার সকালের নাশতায় পরিচিত।",
      aliases: ["paya soup", "paya curry", "পায়ার ঝোল"],
    },
    {
      slug: "khichuri",
      nameBn: "খিচুড়ি",
      nameEn: "Khichuri",
      aboutBn: "চাল আর ডাল একসঙ্গে রান্না করা খাবার। মাংস বা ভর্তার সঙ্গে খাওয়া হয়।",
      aliases: ["khichri", "khichdi", "খিচুরি", "ভুনা খিচুড়ি"],
    },
    {
      slug: "bhapa-pitha",
      nameBn: "ভাপা পিঠা",
      nameEn: "Bhapa Pitha",
      aboutBn: "চালের গুঁড়োর ভেতরে নারকেল-গুড় দিয়ে ভাপে সেদ্ধ করা শীতের পিঠা।",
      aliases: ["bhapa", "vapa pitha", "ভাপা"],
    },
    {
      slug: "patishapta",
      nameBn: "পাটিসাপটা",
      nameEn: "Patishapta",
      aboutBn: "চালের গোলার পাতলা আস্তরে নারকেল বা ক্ষীরের পুর ভরা পিঠা।",
      aliases: ["patisapta", "patishapta pitha", "পাটি সাপটা"],
    },
    {
      slug: "puli-pitha",
      nameBn: "পুলি পিঠা",
      nameEn: "Puli Pitha",
      aboutBn: "চালের গুঁড়োর খোলে নারকেল বা মাংসের পুর ভরে রান্না করা পিঠা।",
      aliases: ["puli", "pulee pitha", "পুলি"],
    },
  ],
  places: [
    {
      slug: "mona-bhai-haleem-dhaka",
      nameBn: "মোনা ভাইয়ের হালিম ও স্যুপ",
      nameEn: "Mona Bhai Haleem and Soup",
      district: "dhaka",
      type: "shop",
      area: "mohammadpur",
      famousFor: ["haleem"],
    },
    {
      slug: "khaza-haleem-dhaka",
      nameBn: "খাজা হালিম",
      nameEn: "Khaza Haleem",
      district: "dhaka",
      type: "shop",
      area: "gopibag",
      famousFor: ["haleem"],
    },
    {
      slug: "mama-haleem-dhaka",
      nameBn: "মামা হালিম",
      nameEn: "Mama Haleem",
      district: "dhaka",
      type: "shop",
      area: "kalabagan",
      famousFor: ["haleem"],
    },
    {
      slug: "decent-bakery-dhaka",
      nameBn: "ডিসেন্ট বেকারি",
      nameEn: "Decent Bakery",
      district: "dhaka",
      type: "bakery",
      area: "dhanmondi",
      famousFor: ["haleem"],
    },
    {
      slug: "nirob-hotel-dhaka",
      nameBn: "নিরব হোটেল",
      nameEn: "Nirob Hotel",
      district: "dhaka",
      type: "restaurant",
      area: "chankharpul",
      famousFor: ["puri-bhaji", "bhorta"],
    },
    {
      slug: "chowrangi-restaurant-dhaka",
      nameBn: "চৌরঙ্গী রেস্টুরেন্ট",
      nameEn: "Chowrangi Restaurant",
      district: "dhaka",
      type: "restaurant",
      area: "banglabazar",
      famousFor: ["luchi"],
    },
    {
      slug: "hirajheel-hotel-dhaka",
      nameBn: "হীরাঝিল হোটেল",
      nameEn: "Hirajheel Hotel",
      district: "dhaka",
      type: "restaurant",
      area: "motijheel",
      famousFor: ["paya", "khichuri"],
    },
    {
      slug: "deshbondhu-sweetmeat-dhaka",
      nameBn: "দেশবন্ধু সুইটমিট",
      nameEn: "Deshbondhu Sweetmeat",
      district: "dhaka",
      type: "shop",
      area: "hathkhola",
      famousFor: ["paratha-bhaji"],
    },
    {
      slug: "bailey-pitha-ghor-dhaka",
      nameBn: "বেইলি পিঠা ঘর",
      nameEn: "Bailey Pitha Ghor",
      district: "dhaka",
      type: "restaurant",
      area: "baily-road",
      famousFor: ["chitoi-pitha", "puli-pitha"],
    },
    {
      slug: "adda-prabartana-dhaka",
      nameBn: "আড্ডা প্রবর্তনা",
      nameEn: "Adda Prabartana",
      district: "dhaka",
      type: "restaurant",
      area: "mohammadpur",
      famousFor: ["bhapa-pitha", "chitoi-pitha", "patishapta"],
    },
    {
      slug: "mirpur-pitha-ghar-dhaka",
      nameBn: "মিরপুর পিঠা ঘর",
      nameEn: "Mirpur Pitha Ghar",
      district: "dhaka",
      type: "shop",
      area: "mirpur",
      famousFor: ["puli-pitha", "patishapta", "chitoi-pitha"],
    },
    {
      slug: "shantinagar-pitha-ghar-dhaka",
      nameBn: "শান্তিনগর পিঠা ঘর অ্যান্ড কাবাব",
      nameEn: "Shantinagar Pitha Ghar and Kabab",
      district: "dhaka",
      type: "restaurant",
      area: "shantinagar",
      famousFor: ["chitoi-pitha", "patishapta"],
    },
    {
      slug: "uttara-pitha-ghar-dhaka",
      nameBn: "উত্তরা পিঠা ঘর",
      nameEn: "Uttara Pitha Ghar",
      district: "dhaka",
      type: "shop",
      area: "uttara",
      famousFor: ["patishapta"],
    },
  ],
  existingAreas: [],
  existingDishes: [{ slug: "green-sweet-meat-dhaka", food: "luchi" }],
  fame: [
    {
      district: "dhaka",
      food: "haleem",
      noteBn: "ঢাকার হালিম",
      sourceUrl: "https://www.tbsnews.net/features/food/5-hearty-haleems-dhaka-city-407646",
    },
    {
      district: "dhaka",
      food: "chitoi-pitha",
      noteBn: "শীতের পিঠা",
      sourceUrl: "https://www.tbsnews.net/feature/food/best-places-get-pitha-winter-186202",
    },
  ],
  fameSources: [],
};
