/**
 * Content outside Dhaka, part 2 (migrations 0021 to 0024): Khulna, Rajshahi, Bogura, Cumilla.
 * Same rules as dhaka-data.ts: only what published articles say, no prices or ratings, nothing
 * from review sites or delivery apps. Sources in docs/content-sources.md.
 */
import type { DhakaSet } from "./dhaka-data";

export const KHULNA_SET: DhakaSet = {
  migration: "0021_seed_khulna.sql",
  number: "0021",
  districtSlug: "khulna",
  areas: [
    { slug: "khulna-city", nameBn: "খুলনা শহর", nameEn: "Khulna city" },
    { slug: "new-market", nameBn: "নিউ মার্কেট", nameEn: "New Market" },
    { slug: "rupsha-ghat", nameBn: "রূপসা ঘাট", nameEn: "Rupsha Ghat" },
  ],
  foods: [
    {
      slug: "roshogolla",
      nameBn: "রসগোল্লা",
      nameEn: "Roshogolla",
      aboutBn: "ছানার গোল মিষ্টি, চিনির রসে ডোবানো।",
      aliases: ["rasgulla", "rosogolla", "rossogolla", "রসগোলা"],
    },
    {
      slug: "shondesh",
      nameBn: "সন্দেশ",
      nameEn: "Shondesh",
      aboutBn: "ছানা ও চিনি দিয়ে তৈরি নরম মিষ্টি।",
      aliases: ["sandesh", "sondesh", "সন্দেশ"],
    },
    {
      slug: "singara",
      nameBn: "সিঙ্গারা",
      nameEn: "Singara",
      aboutBn: "আলু বা মাংসের পুর দেওয়া তেলে ভাজা ত্রিকোণ নাশতা।",
      aliases: ["shingara", "samosa", "shingra", "সমুচা"],
    },
    {
      slug: "ghugni",
      nameBn: "ঘুগনি",
      nameEn: "Ghugni",
      aboutBn: "সেদ্ধ মটর বা ছোলার মসলাদার ঝোল নাশতা।",
      aliases: ["ghugni", "ghuguni", "ঘুগনী"],
    },
  ],
  places: [
    {
      slug: "abbas-hotel-khulna",
      nameBn: "আব্বাস হোটেল",
      nameEn: "Abbas Hotel",
      district: "khulna",
      type: "restaurant",
      area: "khulna-city",
      famousFor: ["chui-jhal"],
    },
    {
      slug: "gesco-kabab-khulna",
      nameBn: "গেসকো কাবাব",
      nameEn: "Gesco Kabab",
      district: "khulna",
      type: "restaurant",
      area: "khulna-city",
      famousFor: ["kabab", "chaap"],
    },
    {
      slug: "indramohan-sweets-khulna",
      nameBn: "ইন্দ্রমোহন সুইটস",
      nameEn: "Indramohan Sweets",
      district: "khulna",
      type: "shop",
      area: "khulna-city",
      famousFor: ["roshogolla", "shondesh"],
    },
    {
      slug: "new-howrah-bakery-khulna",
      nameBn: "নিউ হাওড়া বেকারি",
      nameEn: "New Howrah Bakery",
      district: "khulna",
      type: "bakery",
      area: "new-market",
      famousFor: ["singara", "faluda"],
    },
    {
      slug: "rupsha-ghat-khulna",
      nameBn: "রূপসা ঘাটের নাশতা",
      nameEn: "Rupsha Ghat snacks",
      district: "khulna",
      type: "street_food",
      area: "rupsha-ghat",
      famousFor: ["ghugni"],
    },
  ],
  existingAreas: [],
  existingDishes: [],
  fame: [],
  fameSources: [
    {
      district: "khulna",
      food: "chui-jhal",
      sourceUrl: "https://www.tbsnews.net/features/food/ode-khulna-love-food-1107281",
    },
  ],
};

export const RAJSHAHI_SET: DhakaSet = {
  migration: "0022_seed_rajshahi.sql",
  number: "0022",
  districtSlug: "rajshahi",
  fameSortStart: 60,
  areas: [
    { slug: "new-market", nameBn: "নিউ মার্কেট", nameEn: "New Market" },
    { slug: "laxmipur", nameBn: "লক্ষ্মীপুর", nameEn: "Laxmipur" },
    { slug: "malopara", nameBn: "মালোপাড়া", nameEn: "Malopara" },
    { slug: "ranibazar", nameBn: "রানীবাজার", nameEn: "Ranibazar" },
    { slug: "saheb-bazar", nameBn: "সাহেব বাজার", nameEn: "Saheb Bazar" },
    { slug: "batar-mor", nameBn: "বাটার মোড়", nameEn: "Batar Mor" },
    { slug: "sadhur-mor", nameBn: "সাধুর মোড়", nameEn: "Sadhur Mor" },
  ],
  foods: [
    {
      slug: "puri-burger",
      nameBn: "পুরি বার্গার",
      nameEn: "Puri Burger",
      aboutBn: "পুরির ভেতরে পাকোড়া-সিঙ্গারার কুচি ও সস দেওয়া রাজশাহীর রাস্তার খাবার।",
      aliases: ["puri burger", "puri-burger", "পুরি বার্গার"],
    },
    {
      slug: "seekh-burger",
      nameBn: "সিক বার্গার",
      nameEn: "Seekh Burger",
      aboutBn: "সিক কাবাব ভরা বার্গার। রাজশাহীর সাধুর মোড়ের সন্ধ্যার খাবার।",
      aliases: ["seek burger", "shik burger", "সিখ বার্গার"],
    },
    {
      slug: "kaliza-singara",
      nameBn: "কলিজা সিঙ্গারা",
      nameEn: "Kaliza Singara",
      aboutBn: "গরুর কলিজার পুর দেওয়া সিঙ্গারা। রাজশাহীর পরিচিত নাশতা।",
      aliases: ["koliza singara", "koliji singara", "কলিজা সমুচা", "কলিজা সিংগারা"],
    },
    {
      slug: "chanar-polao",
      nameBn: "ছানার পোলাও",
      nameEn: "Chanar Polao",
      aboutBn: "ছানা দিয়ে তৈরি পোলাওয়ের মতো দেখতে মিষ্টি।",
      aliases: ["chhanar polao", "chana polao", "ছানার পুলাও"],
    },
    {
      slug: "mishti",
      nameBn: "মিষ্টি",
      nameEn: "Mishti",
      aboutBn: "বাংলাদেশের নানা রকম মিষ্টির সাধারণ নাম।",
      aliases: ["sweets", "sweetmeat", "মিষ্টান্ন"],
    },
  ],
  places: [
    {
      slug: "puri-burger-new-market-rajshahi",
      nameBn: "নিউ মার্কেটের পুরি বার্গার",
      nameEn: "New Market puri burger",
      district: "rajshahi",
      type: "street_food",
      area: "new-market",
      famousFor: ["puri-burger"],
    },
    {
      slug: "sadhur-mor-seekh-burger-rajshahi",
      nameBn: "সাধুর মোড়ের সিক বার্গার",
      nameEn: "Sadhur Mor seekh burger",
      district: "rajshahi",
      type: "street_food",
      area: "sadhur-mor",
      famousFor: ["seekh-burger"],
    },
    {
      slug: "haji-restaurant-rajshahi",
      nameBn: "হাজী রেস্টুরেন্ট",
      nameEn: "Haji Restaurant",
      district: "rajshahi",
      type: "restaurant",
      area: "laxmipur",
      famousFor: ["kaliza-singara"],
    },
    {
      slug: "tripti-restaurant-rajshahi",
      nameBn: "তৃপ্তি রেস্টুরেন্ট",
      nameEn: "Tripti Restaurant",
      district: "rajshahi",
      type: "restaurant",
      area: "laxmipur",
      famousFor: ["kaliza-singara"],
    },
    {
      slug: "jorakali-restaurant-rajshahi",
      nameBn: "জোড়াকালী রেস্টুরেন্ট",
      nameEn: "Jorakali Restaurant",
      district: "rajshahi",
      type: "restaurant",
      area: "malopara",
      famousFor: ["luchi"],
    },
    {
      slug: "ranars-sweet-rajshahi",
      nameBn: "রানার মিষ্টি",
      nameEn: "Ranar's Sweet",
      district: "rajshahi",
      type: "shop",
      area: "ranibazar",
      famousFor: ["mishti"],
    },
    {
      slug: "noborup-rajshahi",
      nameBn: "নবরূপ",
      nameEn: "Noborup",
      district: "rajshahi",
      type: "shop",
      area: "saheb-bazar",
      famousFor: ["chanar-polao"],
    },
    {
      slug: "batar-morer-jilapi-rajshahi",
      nameBn: "বাটার মোড়ের জিলাপি",
      nameEn: "Batar Morer Jilapi",
      district: "rajshahi",
      type: "shop",
      area: "batar-mor",
      famousFor: ["jilapi"],
    },
  ],
  existingAreas: [],
  existingDishes: [],
  fame: [
    {
      district: "rajshahi",
      food: "jilapi",
      noteBn: "বাটার মোড়ের জিলাপি",
      sourceUrl: "https://www.tbsnews.net/feature/food/rajshahi-food-you-should-never-miss",
    },
    {
      district: "rajshahi",
      food: "puri-burger",
      noteBn: "নিউ মার্কেটের পুরি বার্গার",
      sourceUrl: "https://www.tbsnews.net/feature/food/rajshahi-food-you-should-never-miss",
    },
  ],
  fameSources: [],
};

export const BOGURA_SET: DhakaSet = {
  migration: "0023_seed_bogura.sql",
  number: "0023",
  districtSlug: "bogura",
  areas: [
    { slug: "bogura-city", nameBn: "বগুড়া শহর", nameEn: "Bogura city" },
    { slug: "nawabbari", nameBn: "নবাববাড়ি", nameEn: "Nawabbari" },
    { slug: "sherpur", nameBn: "শেরপুর", nameEn: "Sherpur" },
    { slug: "jhautala", nameBn: "ঝাউতলা", nameEn: "Jhautala" },
  ],
  foods: [],
  places: [
    {
      slug: "shri-gour-gopal-dadhi-bhandar-bogura",
      nameBn: "শ্রী গৌর গোপাল দধি ও মিষ্টান্ন ভাণ্ডার",
      nameEn: "Shri Gour Gopal Dadhi and Mistanna Bhandar",
      district: "bogura",
      type: "shop",
      area: "nawabbari",
      famousFor: ["doi"],
    },
    {
      slug: "ruchita-bogura",
      nameBn: "রুচিতা",
      nameEn: "Ruchita",
      district: "bogura",
      type: "shop",
      area: "nawabbari",
      famousFor: ["doi"],
    },
    {
      slug: "sherpur-doi-ghar-bogura",
      nameBn: "শেরপুর দই ঘর",
      nameEn: "Sherpur Doi Ghar",
      district: "bogura",
      type: "shop",
      area: "sherpur",
      famousFor: ["doi"],
    },
    {
      slug: "enam-doi-ghar-bogura",
      nameBn: "এনাম দই ঘর",
      nameEn: "Enam Doi Ghar",
      district: "bogura",
      type: "shop",
      area: "jhautala",
      famousFor: ["doi"],
    },
    {
      slug: "asia-sweets-bogura",
      nameBn: "এশিয়া সুইটস",
      nameEn: "Asia Sweets",
      district: "bogura",
      type: "shop",
      area: "bogura-city",
      famousFor: ["doi"],
    },
    {
      slug: "akbaria-bogura",
      nameBn: "আকবরিয়া",
      nameEn: "Akbaria",
      district: "bogura",
      type: "shop",
      area: "bogura-city",
      famousFor: ["doi"],
    },
    {
      slug: "chinipata-bogura",
      nameBn: "চিনিপাতা",
      nameEn: "Chinipata",
      district: "bogura",
      type: "shop",
      area: "bogura-city",
      famousFor: ["doi"],
    },
    {
      slug: "shyamoli-hotel-bogura",
      nameBn: "শ্যামলী হোটেল অ্যান্ড রেস্টুরেন্ট",
      nameEn: "Shyamoli Hotel and Restaurant",
      district: "bogura",
      type: "restaurant",
      area: "bogura-city",
      famousFor: ["doi"],
    },
  ],
  existingAreas: [],
  existingDishes: [],
  fame: [],
  fameSources: [
    { district: "bogura", food: "doi", sourceUrl: "https://www.bssnews.net/district/316161" },
  ],
};

export const CUMILLA_SET: DhakaSet = {
  migration: "0024_seed_cumilla.sql",
  number: "0024",
  districtSlug: "cumilla",
  areas: [
    { slug: "manoharpur", nameBn: "মনোহরপুর", nameEn: "Manoharpur" },
    { slug: "cumilla-city", nameBn: "কুমিল্লা শহর", nameEn: "Cumilla city" },
  ],
  foods: [],
  places: [
    {
      slug: "cumilla-mishti-bhandar-cumilla",
      nameBn: "কুমিল্লা মিষ্টি ভাণ্ডার",
      nameEn: "Cumilla Mishti Bhandar",
      district: "cumilla",
      type: "shop",
      area: "cumilla-city",
      famousFor: ["rasmalai"],
    },
    {
      slug: "bhagwati-peda-bhandar-cumilla",
      nameBn: "ভগবতী পেঁড়া ভাণ্ডার",
      nameEn: "Bhagwati Peda Bhandar",
      district: "cumilla",
      type: "shop",
      area: "cumilla-city",
      famousFor: ["rasmalai"],
    },
    {
      slug: "shital-bhandar-cumilla",
      nameBn: "শীতল ভাণ্ডার",
      nameEn: "Shital Bhandar",
      district: "cumilla",
      type: "shop",
      area: "cumilla-city",
      famousFor: ["rasmalai"],
    },
  ],
  existingAreas: [{ slug: "matri-bhandar-cumilla", area: "manoharpur" }],
  existingDishes: [],
  fame: [],
  fameSources: [
    {
      district: "cumilla",
      food: "rasmalai",
      sourceUrl: "https://www.bssnews.net/district/311066",
    },
  ],
};
